version: '3.8'

services:
  web:
    container_name: ctf
    build:
      context: .
      dockerfile: Dockerfile
      
    image: php:8.1-apache
    volumes:
      - ./src:/var/www/html
      - ./src/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8003:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
    - network-prod

networks:
  network-prod:
    driver: bridge
    external: true